{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sre-copilot.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sre-copilot.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sre-copilot.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicaCount | int }}
  maxReplicas: {{ .Values.hpa.maxReplicaCount | int }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpu | int }}
{{- end }}
