{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sre-copilot.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sre-copilot.labels" . | nindent 4 }}
{{- end }}
